### ISSUE TITLE
Not generating Config Folder / file?

### ISSUE THREAD

**Issue by ejmiv** [brandon3055/PotionIDHelper#1]
I was recommended by multiple sources to use this Potion ID Helper, but I don't see a folder or a file being generated. Is there a specific name for the config file / folder that I need to be aware of?

**Comment by brandon3055** [comment]
The first time you start the game with the mod installed it will generate a file called PotionIdConflicts.txt in your config folder that will contain a list of all id conflicts and give alternate id suggestions.

**Comment by ejmiv** [comment]
Gotcha, thanks for the details on how the mod operates. I was wondering because I just needed a small increase in potions for Ars Magica to fit in (common issue for modpacks with Witchery + Ars2) and I wasn't seeing a configuration file. I appreciate your help.
